[package]
name = "didyoumean"
authors = ["Hisbaan Noorani"]
version = "1.1.1"
edition = "2021"
license = "GPL-3.0"
description = "A CLI spelling corrector"
documentation = "https://github.com/hisbaan/didyoumean"
homepage = "https://github.com/hisbaan/didyoumean"
repository = "https://github.com/hisbaan/didyoumean"
readme = "docs/README.md"
keywords = ["levenshtein", "damerau", "edit-distance", "spelling"]
categories = ["command-line-utilities"]

[[bin]]
name = "dym"
path = "src/main.rs"

[dependencies]
clap = { version = "3.1.10", features = ["derive"] }
colored = { version = "2" }
cli-clipboard = {version = "0.2.1"}
dialoguer = {version = "0.10.0"}
atty = { version = "0.2.14" }

[target.'cfg(unix)'.dependencies]
nix = { version = "0.23.1" }

[dev-dependencies]
criterion = "0.3.5"

[[bench]]
name = "edit_distance"
harness = false
